export type NavSite = {
	title: string;
	desc: string;
	url: string;
	/** 站点图标 URL，留空则用首字母 */
	icon?: string;
	/** 角标，如「推荐」 */
	badge?: string;
	/** 所属标签，需与分组 tags 对应 */
	tags: string[];
	/** 是否待审核（不在前台列表展示，只计入待审核统计） */
	pending?: boolean;
};

export type NavGroup = {
	id: string;
	name: string;
	icon: string;
	/** 分组下的筛选标签，第一项通常是「全部」 */
	tags: string[];
	sites: NavSite[];
};

export type NavPageConfig = {
	title: string;
	description: string;
	/**
	 * 额外的待审核数量（不在 groups 里、仅用于统计展示）
	 * 实际 pending 站点仍可通过 NavSite.pending 标记
	 */
	extraPendingCount?: number;
	groups: NavGroup[];
};

/** 统计已上线站点数 */
export function countPublishedSites(groups: NavGroup[]): number {
	return groups.reduce(
		(sum, group) => sum + group.sites.filter((site) => !site.pending).length,
		0,
	);
}

/** 统计待审核站点数 */
export function countPendingSites(
	groups: NavGroup[],
	extraPendingCount = 0,
): number {
	const marked = groups.reduce(
		(sum, group) => sum + group.sites.filter((site) => site.pending).length,
		0,
	);
	return marked + extraPendingCount;
}

/** 仅收录正规官网 / 开源工具，不含盗版影音与破解资源站 */
export const navPageConfig: NavPageConfig = {
	title: "导航",
	description: "常用站点导航",
	// 额外待审核数量（投稿后可在此累加，或给站点加 pending: true）
	extraPendingCount: 0,
	groups: [
		{
			id: "media",
			name: "影音视听",
			icon: "material-symbols:movie",
			tags: ["全部", "视频", "音乐", "直播", "播客"],
			sites: [
				{
					title: "哔哩哔哩",
					desc: "弹幕视频与二次元内容社区",
					url: "https://www.bilibili.com",
					icon: "https://www.bilibili.com/favicon.ico",
					badge: "推荐",
					tags: ["视频", "直播"],
				},
				{
					title: "YouTube",
					desc: "全球最大视频分享平台",
					url: "https://www.youtube.com",
					icon: "https://www.youtube.com/favicon.ico",
					tags: ["视频", "直播"],
				},
				{
					title: "抖音",
					desc: "短视频与直播平台",
					url: "https://www.douyin.com",
					icon: "https://www.douyin.com/favicon.ico",
					tags: ["视频", "直播"],
				},
				{
					title: "爱奇艺",
					desc: "正版影视综艺在线平台",
					url: "https://www.iqiyi.com",
					icon: "https://www.iqiyi.com/favicon.ico",
					tags: ["视频"],
				},
				{
					title: "腾讯视频",
					desc: "热门影视与会员内容",
					url: "https://v.qq.com",
					icon: "https://v.qq.com/favicon.ico",
					tags: ["视频"],
				},
				{
					title: "优酷",
					desc: "综合视频内容平台",
					url: "https://www.youku.com",
					icon: "https://www.youku.com/favicon.ico",
					tags: ["视频"],
				},
				{
					title: "芒果TV",
					desc: "湖南广电正版视频平台",
					url: "https://www.mgtv.com",
					icon: "https://www.mgtv.com/favicon.ico",
					tags: ["视频"],
				},
				{
					title: "Netflix",
					desc: "国际流媒体影视服务",
					url: "https://www.netflix.com",
					icon: "https://www.netflix.com/favicon.ico",
					tags: ["视频"],
				},
				{
					title: "网易云音乐",
					desc: "发现与分享好音乐",
					url: "https://music.163.com",
					icon: "https://s1.music.126.net/style/favicon.ico",
					badge: "推荐",
					tags: ["音乐", "播客"],
				},
				{
					title: "QQ音乐",
					desc: "正版曲库与在线听歌",
					url: "https://y.qq.com",
					icon: "https://y.qq.com/favicon.ico",
					tags: ["音乐"],
				},
				{
					title: "Spotify",
					desc: "全球音乐流媒体服务",
					url: "https://open.spotify.com",
					icon: "https://open.spotify.com/favicon.ico",
					tags: ["音乐", "播客"],
				},
				{
					title: "Apple Podcasts",
					desc: "播客节目收听入口",
					url: "https://podcasts.apple.com",
					icon: "https://podcasts.apple.com/favicon.ico",
					tags: ["播客"],
				},
			],
		},
		{
			id: "ai",
			name: "人工智能",
			icon: "material-symbols:psychology",
			tags: ["全部", "对话", "绘画", "编程", "搜索"],
			sites: [
				{
					title: "ChatGPT",
					desc: "OpenAI 对话与创作助手",
					url: "https://chatgpt.com",
					icon: "https://chatgpt.com/favicon.ico",
					badge: "推荐",
					tags: ["对话"],
				},
				{
					title: "Claude",
					desc: "Anthropic 智能助手",
					url: "https://claude.ai",
					icon: "https://claude.ai/favicon.ico",
					tags: ["对话", "编程"],
				},
				{
					title: "Gemini",
					desc: "Google 多模态 AI",
					url: "https://gemini.google.com",
					icon: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
					tags: ["对话", "搜索"],
				},
				{
					title: "Grok",
					desc: "xAI 对话助手",
					url: "https://grok.com",
					icon: "https://grok.com/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "Kimi",
					desc: "月之暗面长文本助手",
					url: "https://www.kimi.com",
					icon: "https://www.kimi.com/favicon.ico",
					badge: "推荐",
					tags: ["对话"],
				},
				{
					title: "DeepSeek",
					desc: "深度求索大模型",
					url: "https://chat.deepseek.com",
					icon: "https://chat.deepseek.com/favicon.ico",
					tags: ["对话", "编程"],
				},
				{
					title: "通义千问",
					desc: "阿里云通义大模型",
					url: "https://tongyi.aliyun.com",
					icon: "https://img.alicdn.com/imgextra/i4/O1CN01EfJVFQ1uZPd7W4W6i_!!6000000006051-2-tps-112-112.png",
					badge: "官方",
					tags: ["对话"],
				},
				{
					title: "豆包",
					desc: "字节跳动 AI 助手",
					url: "https://www.doubao.com",
					icon: "https://www.doubao.com/favicon.ico",
					badge: "官方",
					tags: ["对话"],
				},
				{
					title: "文心一言",
					desc: "百度文心大模型",
					url: "https://yiyan.baidu.com",
					icon: "https://yiyan.baidu.com/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "腾讯元宝",
					desc: "腾讯混元 AI 助手",
					url: "https://yuanbao.tencent.com",
					icon: "https://yuanbao.tencent.com/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "腾讯混元",
					desc: "腾讯混元大模型开放平台",
					url: "https://hunyuan.tencent.com",
					icon: "https://hunyuan.tencent.com/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "讯飞星火",
					desc: "科大讯飞认知大模型",
					url: "https://xinghuo.xfyun.cn",
					icon: "https://xinghuo.xfyun.cn/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "智谱清言",
					desc: "ChatGLM 对话助手",
					url: "https://chatglm.cn",
					icon: "https://chatglm.cn/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "天工 AI",
					desc: "昆仑万维天工助手",
					url: "https://www.tiangong.cn",
					icon: "https://www.tiangong.cn/favicon.ico",
					tags: ["对话", "搜索"],
				},
				{
					title: "问小白",
					desc: "元石科技 AI 助手",
					url: "https://www.wenxiaobai.com",
					icon: "https://www.wenxiaobai.com/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "知乎直答",
					desc: "知乎 AI 搜索问答",
					url: "https://www.zhihu.com/xihe",
					icon: "https://static.zhihu.com/heifetz/favicon.ico",
					tags: ["搜索", "对话"],
				},
				{
					title: "C 知道",
					desc: "CSDN AI 技术助手",
					url: "https://www.csdn.net",
					icon: "https://g.csdnimg.cn/static/logo/favicon.ico",
					tags: ["对话", "编程"],
				},
				{
					title: "Microsoft Copilot",
					desc: "微软 AI 助手",
					url: "https://copilot.microsoft.com",
					icon: "https://copilot.microsoft.com/favicon.ico",
					tags: ["对话"],
				},
				{
					title: "Cursor",
					desc: "AI 代码编辑器",
					url: "https://cursor.com",
					icon: "https://cursor.com/favicon.ico",
					badge: "推荐",
					tags: ["编程"],
				},
				{
					title: "GitHub Copilot",
					desc: "GitHub AI 编程助手",
					url: "https://github.com/features/copilot",
					icon: "https://github.com/favicon.ico",
					tags: ["编程"],
				},
				{
					title: "Midjourney",
					desc: "高质量 AI 图像生成",
					url: "https://www.midjourney.com",
					icon: "https://www.midjourney.com/favicon.ico",
					tags: ["绘画"],
				},
				{
					title: "Perplexity",
					desc: "带引用的 AI 搜索",
					url: "https://www.perplexity.ai",
					icon: "https://www.perplexity.ai/favicon.ico",
					tags: ["搜索", "对话"],
				},
			],
		},
		{
			id: "office",
			name: "办公工具",
			icon: "material-symbols:work",
			tags: ["全部", "综合", "协作", "文档", "转换"],
			sites: [
				{
					title: "腾讯帮小忙",
					desc: "腾讯在线实用小工具合集",
					url: "https://tool.browser.qq.com",
					icon: "https://tool.browser.qq.com/favicon.ico",
					badge: "推荐",
					tags: ["综合", "转换"],
				},
				{
					title: "飞书",
					desc: "一站式协作办公套件",
					url: "https://www.feishu.cn",
					icon: "https://www.feishu.cn/favicon.ico",
					badge: "推荐",
					tags: ["协作", "文档"],
				},
				{
					title: "钉钉",
					desc: "企业沟通与协同平台",
					url: "https://www.dingtalk.com",
					icon: "https://www.dingtalk.com/favicon.ico",
					tags: ["协作"],
				},
				{
					title: "Notion",
					desc: "全能笔记与知识库",
					url: "https://www.notion.so",
					icon: "https://www.notion.so/images/favicon.ico",
					tags: ["文档"],
				},
				{
					title: "语雀",
					desc: "专业云端知识库",
					url: "https://www.yuque.com",
					icon: "https://www.yuque.com/favicon.ico",
					tags: ["文档"],
				},
				{
					title: "腾讯文档",
					desc: "在线协作文档表格",
					url: "https://docs.qq.com",
					icon: "https://docs.qq.com/favicon.ico",
					tags: ["文档", "协作"],
				},
				{
					title: "金山文档",
					desc: "WPS 在线办公",
					url: "https://www.kdocs.cn",
					icon: "https://www.kdocs.cn/favicon.ico",
					tags: ["文档"],
				},
				{
					title: "石墨文档",
					desc: "轻量协作文档",
					url: "https://shimo.im",
					icon: "https://shimo.im/favicon.ico",
					tags: ["文档", "协作"],
				},
				{
					title: "ProcessOn",
					desc: "在线流程图思维导图",
					url: "https://www.processon.com",
					icon: "https://www.processon.com/favicon.ico",
					tags: ["文档"],
				},
				{
					title: "DeepL",
					desc: "高质量机器翻译",
					url: "https://www.deepl.com",
					icon: "https://www.deepl.com/favicon.ico",
					tags: ["转换"],
				},
				{
					title: "有道翻译",
					desc: "多语种翻译与词典",
					url: "https://fanyi.youdao.com",
					icon: "https://shared.ydstatic.com/images/favicon.ico",
					tags: ["转换"],
				},
				{
					title: "iLovePDF",
					desc: "PDF 合并压缩转换",
					url: "https://www.ilovepdf.com",
					icon: "https://www.ilovepdf.com/img/favicons-pdf/favicon-32x32.png",
					tags: ["转换"],
				},
				{
					title: "Smallpdf",
					desc: "简洁 PDF 在线工具",
					url: "https://smallpdf.com",
					icon: "https://smallpdf.com/favicon.ico",
					tags: ["转换"],
				},
				{
					title: "Convertio",
					desc: "在线文件格式转换",
					url: "https://convertio.co",
					icon: "https://convertio.co/favicon.ico",
					tags: ["转换", "综合"],
				},
				{
					title: "Dillinger",
					desc: "在线 Markdown 编辑器",
					url: "https://dillinger.io",
					icon: "https://dillinger.io/favicon.ico",
					tags: ["文档", "综合"],
				},
				{
					title: "草料二维码",
					desc: "二维码生成与管理",
					url: "https://cli.im",
					icon: "https://cli.im/favicon.ico",
					tags: ["综合"],
				},
			],
		},
		{
			id: "dev",
			name: "程序开发",
			icon: "material-symbols:code",
			tags: ["全部", "托管", "文档", "部署", "工具"],
			sites: [
				{
					title: "GitHub",
					desc: "全球最大代码托管平台",
					url: "https://github.com",
					icon: "https://github.com/favicon.ico",
					badge: "推荐",
					tags: ["托管"],
				},
				{
					title: "GitLab",
					desc: "DevOps 代码托管平台",
					url: "https://gitlab.com",
					icon: "https://gitlab.com/favicon.ico",
					tags: ["托管"],
				},
				{
					title: "Gitee",
					desc: "国内代码托管与协作",
					url: "https://gitee.com",
					icon: "https://gitee.com/favicon.ico",
					tags: ["托管"],
				},
				{
					title: "MDN",
					desc: "权威 Web 技术文档",
					url: "https://developer.mozilla.org",
					icon: "https://developer.mozilla.org/favicon-48x48.png",
					badge: "推荐",
					tags: ["文档"],
				},
				{
					title: "Stack Overflow",
					desc: "程序员问答社区",
					url: "https://stackoverflow.com",
					icon: "https://stackoverflow.com/favicon.ico",
					tags: ["文档"],
				},
				{
					title: "npm",
					desc: "JavaScript 包管理仓库",
					url: "https://www.npmjs.com",
					icon: "https://www.npmjs.com/favicon.ico",
					tags: ["工具"],
				},
				{
					title: "Docker Hub",
					desc: "容器镜像仓库",
					url: "https://hub.docker.com",
					icon: "https://hub.docker.com/favicon.ico",
					tags: ["工具", "部署"],
				},
				{
					title: "Vercel",
					desc: "前端应用一键部署",
					url: "https://vercel.com",
					icon: "https://vercel.com/favicon.ico",
					tags: ["部署"],
				},
				{
					title: "Cloudflare",
					desc: "CDN、DNS 与边缘计算",
					url: "https://www.cloudflare.com",
					icon: "https://www.cloudflare.com/favicon.ico",
					tags: ["部署"],
				},
				{
					title: "Can I Use",
					desc: "浏览器兼容性查询",
					url: "https://caniuse.com",
					icon: "https://caniuse.com/img/favicon-128.png",
					tags: ["工具", "文档"],
				},
				{
					title: "Regex101",
					desc: "正则表达式调试器",
					url: "https://regex101.com",
					icon: "https://regex101.com/favicon.ico",
					tags: ["工具"],
				},
				{
					title: "Astro",
					desc: "内容驱动的现代 Web 框架",
					url: "https://astro.build",
					icon: "https://astro.build/favicon.svg",
					tags: ["文档"],
				},
			],
		},
		{
			id: "design",
			name: "设计工具",
			icon: "material-symbols:palette",
			tags: ["全部", "在线设计", "图标", "素材", "配色"],
			sites: [
				{
					title: "Figma",
					desc: "协作式界面设计工具",
					url: "https://www.figma.com",
					icon: "https://static.figma.com/app/icon/1/favicon.png",
					badge: "推荐",
					tags: ["在线设计"],
				},
				{
					title: "即时设计",
					desc: "国内专业 UI 协作设计工具",
					url: "https://js.design",
					icon: "https://img.js.design/assets/web/favicon.ico",
					badge: "推荐",
					tags: ["在线设计"],
				},
				{
					title: "稿定设计",
					desc: "海报电商新媒体在线设计",
					url: "https://www.gaoding.com",
					icon: "https://cdn.dancf.com/fe-assets/img/favicon.ico",
					tags: ["在线设计"],
				},
				{
					title: "图怪兽",
					desc: "在线海报与平面作图工具",
					url: "https://818ps.com",
					icon: "https://818ps.com/favicon.ico",
					tags: ["在线设计"],
				},
				{
					title: "创客贴",
					desc: "模板化平面设计工具",
					url: "https://www.chuangkit.com",
					icon: "https://www.chuangkit.com/favicon.ico",
					tags: ["在线设计"],
				},
				{
					title: "Canva",
					desc: "国际在线平面设计平台",
					url: "https://www.canva.com",
					icon: "https://www.canva.com/favicon.ico",
					tags: ["在线设计"],
				},
				{
					title: "Adobe Color",
					desc: "配色方案生成与探索",
					url: "https://color.adobe.com",
					icon: "https://color.adobe.com/favicon.ico",
					tags: ["配色"],
				},
				{
					title: "中国色",
					desc: "中国传统色彩手册",
					url: "https://zhongguose.com",
					icon: "https://zhongguose.com/img/favicon.ico",
					tags: ["配色"],
				},
				{
					title: "hue.tools",
					desc: "开发者友好的配色工具",
					url: "https://hue.tools",
					icon: "https://hue.tools/favicon.ico",
					tags: ["配色"],
				},
				{
					title: "Coolors",
					desc: "快速生成配色方案",
					url: "https://coolors.co",
					icon: "https://coolors.co/assets/img/favicon.png",
					tags: ["配色"],
				},
				{
					title: "Iconify",
					desc: "海量开源图标集合",
					url: "https://icon-sets.iconify.design",
					icon: "https://icon-sets.iconify.design/favicon.svg",
					tags: ["图标"],
				},
				{
					title: "iconfont",
					desc: "阿里巴巴矢量图标库",
					url: "https://www.iconfont.cn",
					icon: "https://www.iconfont.cn/favicon.ico",
					tags: ["图标"],
				},
				{
					title: "Unsplash",
					desc: "高质量免费图片素材",
					url: "https://unsplash.com",
					icon: "https://unsplash.com/favicon.ico",
					tags: ["素材"],
				},
				{
					title: "Pexels",
					desc: "免费图片与视频素材",
					url: "https://www.pexels.com",
					icon: "https://www.pexels.com/favicon.ico",
					tags: ["素材"],
				},
				{
					title: "爱给网",
					desc: "音效素材与设计资源",
					url: "https://www.aigei.com",
					icon: "https://www.aigei.com/favicon.ico",
					tags: ["素材"],
				},
				{
					title: "TinyPNG",
					desc: "智能压缩 PNG / JPEG",
					url: "https://tinypng.com",
					icon: "https://tinypng.com/images/favicon.ico",
					tags: ["素材"],
				},
				{
					title: "Remove.bg",
					desc: "一键智能抠图",
					url: "https://www.remove.bg",
					icon: "https://www.remove.bg/favicon.ico",
					tags: ["素材"],
				},
				{
					title: "GitHub Socialify",
					desc: "为仓库生成社交预览图",
					url: "https://socialify.git.ci",
					icon: "https://socialify.git.ci/favicon.ico",
					tags: ["在线设计"],
				},
			],
		},
		{
			id: "search",
			name: "搜索工具",
			icon: "material-symbols:search",
			tags: ["全部", "综合", "学术", "开发"],
			sites: [
				{
					title: "Google",
					desc: "全球综合搜索引擎",
					url: "https://www.google.com",
					icon: "https://www.google.com/favicon.ico",
					badge: "推荐",
					tags: ["综合"],
				},
				{
					title: "Bing",
					desc: "微软搜索引擎",
					url: "https://www.bing.com",
					icon: "https://www.bing.com/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "百度",
					desc: "中文综合搜索",
					url: "https://www.baidu.com",
					icon: "https://www.baidu.com/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "DuckDuckGo",
					desc: "注重隐私的搜索引擎",
					url: "https://duckduckgo.com",
					icon: "https://duckduckgo.com/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "秘塔 AI 搜索",
					desc: "无广告 AI 搜索",
					url: "https://metaso.cn",
					icon: "https://metaso.cn/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "Google Scholar",
					desc: "学术文献搜索",
					url: "https://scholar.google.com",
					icon: "https://scholar.google.com/favicon.ico",
					tags: ["学术"],
				},
				{
					title: "Semantic Scholar",
					desc: "AI 学术论文检索",
					url: "https://www.semanticscholar.org",
					icon: "https://www.semanticscholar.org/favicon.ico",
					tags: ["学术"],
				},
				{
					title: "中国知网",
					desc: "学术期刊与文献数据库",
					url: "https://www.cnki.net",
					icon: "https://www.cnki.net/favicon.ico",
					tags: ["学术"],
				},
				{
					title: "GitHub Search",
					desc: "代码与仓库搜索",
					url: "https://github.com/search",
					icon: "https://github.com/favicon.ico",
					tags: ["开发"],
				},
			],
		},
		{
			id: "learn",
			name: "学习充电",
			icon: "material-symbols:school",
			tags: ["全部", "综合", "课程", "编程", "外语"],
			sites: [
				{
					title: "中国知网",
					desc: "学术期刊论文检索平台",
					url: "https://www.cnki.net",
					icon: "https://www.cnki.net/favicon.ico",
					badge: "推荐",
					tags: ["综合"],
				},
				{
					title: "我要自学网",
					desc: "职业技能视频学习平台",
					url: "https://www.51zxw.net",
					icon: "https://www.51zxw.net/favicon.ico",
					tags: ["课程", "综合"],
				},
				{
					title: "Class Central",
					desc: "全球慕课课程聚合搜索",
					url: "https://www.classcentral.com",
					icon: "https://www.classcentral.com/favicon.ico",
					tags: ["课程", "综合"],
				},
				{
					title: "中国大学 MOOC",
					desc: "国内高校慕课平台",
					url: "https://www.icourse163.org",
					icon: "https://www.icourse163.org/favicon.ico",
					badge: "推荐",
					tags: ["课程"],
				},
				{
					title: "Coursera",
					desc: "国际在线课程平台",
					url: "https://www.coursera.org",
					icon: "https://www.coursera.org/favicon.ico",
					tags: ["课程"],
				},
				{
					title: "中国教育在线",
					desc: "教育资讯与升学服务",
					url: "https://www.eol.cn",
					icon: "https://www.eol.cn/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "网易公开课",
					desc: "公开课与精品课程",
					url: "https://open.163.com",
					icon: "https://open.163.com/favicon.ico",
					tags: ["课程"],
				},
				{
					title: "GeoGebra",
					desc: "数学几何代数互动学习",
					url: "https://www.geogebra.org",
					icon: "https://www.geogebra.org/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "ArchDaily",
					desc: "建筑资讯与设计灵感",
					url: "https://www.archdaily.com",
					icon: "https://www.archdaily.com/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "北大法宝",
					desc: "法律法规检索平台",
					url: "https://www.pkulaw.com",
					icon: "https://www.pkulaw.com/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "Musicca",
					desc: "在线乐理与音乐学习",
					url: "https://www.musicca.com",
					icon: "https://www.musicca.com/favicon.ico",
					tags: ["综合"],
				},
				{
					title: "LeetCode",
					desc: "算法刷题与面试准备",
					url: "https://leetcode.cn",
					icon: "https://leetcode.cn/favicon.ico",
					tags: ["编程"],
				},
				{
					title: "菜鸟教程",
					desc: "入门友好的编程教程",
					url: "https://www.runoob.com",
					icon: "https://www.runoob.com/favicon.ico",
					tags: ["编程"],
				},
				{
					title: "freeCodeCamp",
					desc: "免费开源编程课程",
					url: "https://www.freecodecamp.org",
					icon: "https://www.freecodecamp.org/favicon.ico",
					tags: ["编程", "课程"],
				},
				{
					title: "Duolingo",
					desc: "游戏化外语学习",
					url: "https://www.duolingo.com",
					icon: "https://www.duolingo.com/favicon.ico",
					tags: ["外语"],
				},
				{
					title: "扇贝单词",
					desc: "英语单词打卡学习",
					url: "https://www.shanbay.com",
					icon: "https://www.shanbay.com/favicon.ico",
					tags: ["外语"],
				},
			],
		},
		{
			id: "life",
			name: "生活服务",
			icon: "material-symbols:home",
			tags: ["全部", "出行", "购物", "社交", "地图"],
			sites: [
				{
					title: "12306",
					desc: "铁路官方购票平台",
					url: "https://www.12306.cn",
					icon: "https://www.12306.cn/favicon.ico",
					badge: "推荐",
					tags: ["出行"],
				},
				{
					title: "快递 100",
					desc: "快递物流查询",
					url: "https://www.kuaidi100.com",
					icon: "https://www.kuaidi100.com/favicon.ico",
					tags: ["出行"],
				},
				{
					title: "高德地图",
					desc: "导航与出行服务",
					url: "https://www.amap.com",
					icon: "https://www.amap.com/favicon.ico",
					tags: ["地图", "出行"],
				},
				{
					title: "百度地图",
					desc: "地图搜索与路线规划",
					url: "https://map.baidu.com",
					icon: "https://map.baidu.com/favicon.ico",
					tags: ["地图"],
				},
				{
					title: "淘宝",
					desc: "综合电商购物平台",
					url: "https://www.taobao.com",
					icon: "https://www.taobao.com/favicon.ico",
					tags: ["购物"],
				},
				{
					title: "京东",
					desc: "正品电商与物流",
					url: "https://www.jd.com",
					icon: "https://www.jd.com/favicon.ico",
					tags: ["购物"],
				},
				{
					title: "美团",
					desc: "本地生活与外卖",
					url: "https://www.meituan.com",
					icon: "https://www.meituan.com/favicon.ico",
					tags: ["购物", "出行"],
				},
				{
					title: "知乎",
					desc: "问答与深度内容社区",
					url: "https://www.zhihu.com",
					icon: "https://static.zhihu.com/heifetz/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "微博",
					desc: "社交媒体与热点资讯",
					url: "https://weibo.com",
					icon: "https://weibo.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "小红书",
					desc: "生活方式分享社区",
					url: "https://www.xiaohongshu.com",
					icon: "https://www.xiaohongshu.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "豆瓣",
					desc: "书影音评分与社区",
					url: "https://www.douban.com",
					icon: "https://www.douban.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "百度贴吧",
					desc: "兴趣主题社区",
					url: "https://tieba.baidu.com",
					icon: "https://tieba.baidu.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "虎扑",
					desc: "体育与兴趣社区",
					url: "https://www.hupu.com",
					icon: "https://www.hupu.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "今日头条",
					desc: "资讯推荐平台",
					url: "https://www.toutiao.com",
					icon: "https://www.toutiao.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "即刻",
					desc: "兴趣圈子社交",
					url: "https://web.okjike.com",
					icon: "https://web.okjike.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "脉脉",
					desc: "职场社交网络",
					url: "https://maimai.cn",
					icon: "https://maimai.cn/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "LOFTER",
					desc: "兴趣创作与同好社区",
					url: "https://www.lofter.com",
					icon: "https://www.lofter.com/favicon.ico",
					tags: ["社交"],
				},
				{
					title: "QQ 空间",
					desc: "腾讯社交空间",
					url: "https://qzone.qq.com",
					icon: "https://qzone.qq.com/favicon.ico",
					tags: ["社交"],
				},
			],
		},
		{
			id: "cloud",
			name: "网盘存储",
			icon: "material-symbols:cloud",
			tags: ["全部", "国内", "国际"],
			sites: [
				{
					title: "百度网盘",
					desc: "国内主流网盘服务",
					url: "https://pan.baidu.com",
					icon: "https://pan.baidu.com/favicon.ico",
					tags: ["国内"],
				},
				{
					title: "阿里云盘",
					desc: "不限速网盘服务",
					url: "https://www.alipan.com",
					icon: "https://www.alipan.com/favicon.ico",
					badge: "推荐",
					tags: ["国内"],
				},
				{
					title: "夸克网盘",
					desc: "夸克智能网盘",
					url: "https://pan.quark.cn",
					icon: "https://pan.quark.cn/favicon.ico",
					tags: ["国内"],
				},
				{
					title: "坚果云",
					desc: "同步盘与团队协作",
					url: "https://www.jianguoyun.com",
					icon: "https://www.jianguoyun.com/favicon.ico",
					tags: ["国内"],
				},
				{
					title: "OneDrive",
					desc: "微软云存储",
					url: "https://onedrive.live.com",
					icon: "https://onedrive.live.com/favicon.ico",
					tags: ["国际"],
				},
				{
					title: "Google Drive",
					desc: "谷歌云端硬盘",
					url: "https://drive.google.com",
					icon: "https://ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png",
					tags: ["国际"],
				},
			],
		},
		{
			id: "game",
			name: "游戏平台",
			icon: "material-symbols:sports-esports",
			tags: ["全部", "商店", "厂商", "社区", "云游戏"],
			sites: [
				{
					title: "Steam",
					desc: "全球最大 PC 游戏平台",
					url: "https://store.steampowered.com",
					icon: "https://store.steampowered.com/favicon.ico",
					badge: "推荐",
					tags: ["商店"],
				},
				{
					title: "Epic Games",
					desc: "Epic 游戏商店",
					url: "https://store.epicgames.com",
					icon: "https://store.epicgames.com/favicon.ico",
					tags: ["商店"],
				},
				{
					title: "itch.io",
					desc: "独立游戏发行平台",
					url: "https://itch.io",
					icon: "https://itch.io/favicon.ico",
					tags: ["商店", "社区"],
				},
				{
					title: "Xbox",
					desc: "微软 Xbox 游戏平台",
					url: "https://www.xbox.com",
					icon: "https://www.xbox.com/favicon.ico",
					tags: ["商店"],
				},
				{
					title: "PlayStation",
					desc: "索尼 PlayStation 官方",
					url: "https://www.playstation.com",
					icon: "https://www.playstation.com/favicon.ico",
					tags: ["商店"],
				},
				{
					title: "Nintendo",
					desc: "任天堂官方商店",
					url: "https://www.nintendo.com",
					icon: "https://www.nintendo.com/favicon.ico",
					tags: ["商店", "厂商"],
				},
				{
					title: "Battle.net",
					desc: "暴雪游戏平台",
					url: "https://battle.net",
					icon: "https://battle.net/favicon.ico",
					tags: ["商店", "厂商"],
				},
				{
					title: "米哈游",
					desc: "原神 / 崩铁等官方入口",
					url: "https://www.mihoyo.com",
					icon: "https://www.mihoyo.com/favicon.ico",
					tags: ["厂商"],
				},
				{
					title: "网易游戏",
					desc: "网易游戏官方中心",
					url: "https://game.163.com",
					icon: "https://game.163.com/favicon.ico",
					tags: ["厂商"],
				},
				{
					title: "TapTap",
					desc: "游戏发现与社区",
					url: "https://www.taptap.cn",
					icon: "https://www.taptap.cn/favicon.ico",
					tags: ["社区", "商店"],
				},
				{
					title: "篝火营地",
					desc: "游戏媒体与玩家社区",
					url: "https://www.gouhuo.qq.com",
					icon: "https://www.gouhuo.qq.com/favicon.ico",
					tags: ["社区"],
				},
				{
					title: "GeForce NOW",
					desc: "英伟达云游戏平台",
					url: "https://www.nvidia.com/zh-cn/geforce-now/",
					icon: "https://www.nvidia.com/favicon.ico",
					tags: ["云游戏"],
				},
			],
		},
	],
};
